//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ead_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interest
    {
        public string Username { get; set; }
        public Nullable<int> Action { get; set; }
        public Nullable<int> Cell { get; set; }
        public Nullable<int> Music { get; set; }
        public Nullable<int> Games { get; set; }
        public Nullable<int> Quote { get; set; }
        public Nullable<int> Sports { get; set; }
        public Nullable<int> Technology { get; set; }
    
        public virtual User User { get; set; }
    }
}
